### ISSUE TITLE
Query regarding Hindi documents

### ISSUE THREAD

**Issue by alkakhurana** [kaushal0494/ZmBART#1]
Hi,

Which hindi documents have been used as test set documents for the method ZmBART?
What constraints are applied on summary generation - number of words or number of sentences?

Thanks
Alka

**Comment by kaushal0494** [comment]
Hi @alkakhurana  , Thank you for the query. 
>Which Hindi documents have been used as test set documents for the method ZmBART?

All the details of the dataset can be found in the paper: https://arxiv.org/pdf/2106.01597.pdf

>What constraints are applied on summary generation - number of words or number of sentences?  

The number of words. We use the standard bean search algorithm with beam size 3. The model stops generating the next word if the EOS token hit if not the maximum allowed sentence length was set to 100.  

Let me know if you want more details. Thank you!

**Comment by alkakhurana** [comment]
In the paper https://arxiv.org/pdf/2106.01597.pdf, training/validation/test splits for Hindi language are 1k/1k/5k respectively. Which 5k documents are used for testing the model? Required for fair comparison with the model.

**Comment by kaushal0494** [comment]
Thank you for providing more clarification to the question. 
We are in the process of releasing the cleaned version of the code, ZmBART generated output files and all the pre-processed datasets (as you asked) in the next few weeks. I will let you know as soon as it is online.

**Comment by alkakhurana** [comment]
Thank you.

**Comment by kaushal0494** [comment]
@alkakhurana, my apologies for the long delay.
All the informations are available in the README.md file now.
Thank you!
