### ISSUE TITLE
zmbart languages support

### ISSUE THREAD

**Issue by Aniruddha-JU** [kaushal0494/ZmBART#3]
I am asking about the languages supported in zmbart checkpoint. Is it only supported Hindi or Japanese? and does it it is pre-trained on mbart-large-cc-25 model?

**Comment by kaushal0494** [comment]
Hi @Aniruddha-JU  Thank you for the message. Yes, Currently it supports only Hindi and Japanese Languages. In case If you are looking for other languages- we are currently, working in that direction. We will be releasing a model which supports 30 languages (including 10 Indian languages) based on mT5 but it will take 2-3 months. Yes, the ZmBART is trined on mbart-CC-25 checkpoint.
